// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Simando.Infrastructure.Persistence;

#nullable disable

namespace Simando.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SimandoDbContext))]
    [Migration("20260808215446_RemoveCompanyNamaGrup")]
    partial class RemoveCompanyNamaGrup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("company_nomor_seq");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claim");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claim_user_id");

                    b.ToTable("user_claim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_login");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_login_user_id");

                    b.ToTable("user_login", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_token");

                    b.ToTable("user_token", (string)null);
                });

            modelBuilder.Entity("Simando.Domain.Audit.StatusEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<byte?>("FromStage")
                        .HasColumnType("smallint")
                        .HasColumnName("from_stage");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("from_status");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<byte>("ToStage")
                        .HasColumnType("smallint")
                        .HasColumnName("to_stage");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("to_status");

                    b.Property<Guid?>("WorkflowStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_step_id");

                    b.HasKey("Id")
                        .HasName("pk_status_event");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_status_event_actor_id");

                    b.HasIndex("WorkflowStepId")
                        .HasDatabaseName("ix_status_event_workflow_step_id");

                    b.HasIndex("CompanyId", "OccurredAt")
                        .HasDatabaseName("ix_status_event_company_id_occurred_at");

                    b.ToTable("status_event", null, t =>
                        {
                            t.HasCheckConstraint("ck_status_event_comment_required_on_revisi_tolak", "(action not in ('Revisi', 'Tolak')) or (comment is not null)");
                        });
                });

            modelBuilder.Entity("Simando.Domain.Directory.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alamat");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<byte>("CurrentStage")
                        .HasColumnType("smallint")
                        .HasColumnName("current_stage");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Fax")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("fax");

                    b.Property<Guid>("IndustryTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("industry_type_id");

                    b.Property<string>("KodePos")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("kode_pos");

                    b.Property<Point>("Location")
                        .HasColumnType("geography(Point,4326)")
                        .HasColumnName("location");

                    b.Property<string>("NamaPerusahaan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nama_perusahaan");

                    b.Property<string>("Nomor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("nomor");

                    b.Property<int>("NomorSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("nomor_seq")
                        .HasDefaultValueSql("nextval('company_nomor_seq')");

                    b.Property<string>("Npwp")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("npwp");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Telp")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telp");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VillageId")
                        .HasColumnType("uuid")
                        .HasColumnName("village_id");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_company");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_company_created_by");

                    b.HasIndex("IndustryTypeId")
                        .HasDatabaseName("ix_company_industry_type_id");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_company_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("Nomor")
                        .IsUnique()
                        .HasDatabaseName("ix_company_nomor");

                    b.HasIndex("NomorSeq")
                        .IsUnique()
                        .HasDatabaseName("ix_company_nomor_seq");

                    b.HasIndex("VillageId")
                        .HasDatabaseName("ix_company_village_id");

                    b.HasIndex("AreaId", "CurrentStage", "Status")
                        .HasDatabaseName("ix_company_area_id_current_stage_status");

                    b.ToTable("company", (string)null);
                });

            modelBuilder.Entity("Simando.Domain.Directory.CompanyContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Facebook")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("facebook");

                    b.Property<string>("Instagram")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("instagram");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Jabatan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("jabatan");

                    b.Property<string>("LinkedIn")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("linkedin");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nama");

                    b.Property<string>("NoHp")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("no_hp");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_company_contact");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_company_contact_company_id");

                    b.ToTable("company_contact", (string)null);
                });

            modelBuilder.Entity("Simando.Domain.Directory.Plotting", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Kawasan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kawasan");

                    b.Property<string>("PosisiPelanggan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("posisi_pelanggan");

                    b.Property<Guid>("SalesUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_user_id");

                    b.HasKey("CompanyId")
                        .HasName("pk_plotting");

                    b.HasIndex("SalesUserId")
                        .HasDatabaseName("ix_plotting_sales_user_id");

                    b.ToTable("plotting", (string)null);
                });

            modelBuilder.Entity("Simando.Domain.Geography.District", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BpsCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("bps_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("RegencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("regency_id");

                    b.HasKey("Id")
                        .HasName("pk_district");

                    b.HasIndex("RegencyId", "BpsCode")
                        .IsUnique()
                        .HasDatabaseName("ix_district_regency_id_bps_code")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("district", (string)null);
                });

            modelBuilder.Entity("Simando.Domain.Geography.Province", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BpsCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("bps_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_province");

                    b.HasIndex("BpsCode")
                        .IsUnique()
                        .HasDatabaseName("ix_province_bps_code")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("province", (string)null);
                });

            modelBuilder.Entity("Simando.Domain.Geography.Regency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BpsCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("bps_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid")
                        .HasColumnName("province_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_regency");

                    b.HasIndex("ProvinceId", "BpsCode")
                        .IsUnique()
                        .HasDatabaseName("ix_regency_province_id_bps_code")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("regency", (string)null);
                });

            modelBuilder.Entity("Simando.Domain.Geography.Village", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BpsCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("bps_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid")
                        .HasColumnName("district_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_village");

                    b.HasIndex("DistrictId", "BpsCode")
                        .IsUnique()
                        .HasDatabaseName("ix_village_district_id_bps_code")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("village", (string)null);
                });

            modelBuilder.Entity("Simando.Domain.MasterData.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("iso_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_country");

                    b.HasIndex("IsoCode")
                        .IsUnique()
                        .HasDatabaseName("ix_country_iso_code")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("country", (string)null);
                });

            modelBuilder.Entity("Simando.Domain.MasterData.DocumentNumberCounter", b =>
                {
                    b.Property<string>("DocumentType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("document_type");

                    b.Property<string>("ScopeKey")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("scope_key");

                    b.Property<string>("PeriodKey")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("period_key");

                    b.Property<int>("NextSeq")
                        .HasColumnType("integer")
                        .HasColumnName("next_seq");

                    b.HasKey("DocumentType", "ScopeKey", "PeriodKey")
                        .HasName("pk_document_number_counter");

                    b.ToTable("document_number_counter", (string)null);
                });

            modelBuilder.Entity("Simando.Domain.MasterData.FuelType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_fuel_type");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_fuel_type_name")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("fuel_type", (string)null);
                });

            modelBuilder.Entity("Simando.Domain.MasterData.IndustryType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContohProduk")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contoh_produk");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_industry_type");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_industry_type_name")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("industry_type", (string)null);
                });

            modelBuilder.Entity("Simando.Domain.MasterData.MeterSize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("GSize")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("g_size");

                    b.Property<decimal>("MaxFlow")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("max_flow");

                    b.Property<decimal>("NominalFlow")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("nominal_flow");

                    b.Property<decimal>("PressureRating")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("pressure_rating");

                    b.HasKey("Id")
                        .HasName("pk_meter_size");

                    b.HasIndex("GSize")
                        .IsUnique()
                        .HasDatabaseName("ix_meter_size_g_size")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("meter_size", (string)null);
                });

            modelBuilder.Entity("Simando.Domain.MasterData.MrsSpec", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_mrs_spec");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_mrs_spec_name")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("mrs_spec", (string)null);
                });

            modelBuilder.Entity("Simando.Domain.MasterData.ReasonCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_reason_category");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_reason_category_name")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("reason_category", (string)null);
                });

            modelBuilder.Entity("Simando.Domain.MasterData.ReferenceDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlobKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("blob_key");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_reference_document");

                    b.HasIndex("Name", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_reference_document_name_version");

                    b.ToTable("reference_document", (string)null);
                });

            modelBuilder.Entity("Simando.Domain.MasterData.Segment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_segment");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_segment_name")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("segment", (string)null);
                });

            modelBuilder.Entity("Simando.Domain.MasterData.UnitOfMeasure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dimension");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_unit_of_measure");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_unit_of_measure_code")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("unit_of_measure", (string)null);
                });

            modelBuilder.Entity("Simando.Domain.MasterData.UnitSetMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("set_code");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("pk_unit_set_member");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_unit_set_member_unit_id");

                    b.HasIndex("SetCode", "UnitId")
                        .IsUnique()
                        .HasDatabaseName("ix_unit_set_member_set_code_unit_id");

                    b.ToTable("unit_set_member", (string)null);
                });

            modelBuilder.Entity("Simando.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_id");

                    b.HasKey("Id")
                        .HasName("pk_notification");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_notification_company_id");

                    b.HasIndex("RecipientUserId", "ReadAt")
                        .HasDatabaseName("ix_notification_recipient_user_id_read_at");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("Simando.Domain.Organisation.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("region_id");

                    b.HasKey("Id")
                        .HasName("pk_area");

                    b.HasIndex("RegionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_area_region_id_code");

                    b.ToTable("area", (string)null);
                });

            modelBuilder.Entity("Simando.Domain.Organisation.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_region");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_region_code");

                    b.ToTable("region", (string)null);
                });

            modelBuilder.Entity("Simando.Domain.Security.RoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("AssignedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("region_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_role_assignment");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("ix_user_role_assignment_area_id");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("ix_user_role_assignment_region_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_role_assignment_user_id");

                    b.ToTable("user_role_assignment", (string)null);
                });

            modelBuilder.Entity("Simando.Domain.Workflow.WorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("FinalStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("final_status");

                    b.Property<string>("ReviewerCount")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("reviewer_count");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id")
                        .HasName("pk_workflow_instance");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_workflow_instance_company_id");

                    b.ToTable("workflow_instance", (string)null);
                });

            modelBuilder.Entity("Simando.Domain.Workflow.WorkflowStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acted_at");

                    b.Property<Guid?>("ActedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("acted_by");

                    b.Property<string>("Action")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_user_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer")
                        .HasColumnName("step_order");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_instance_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_step");

                    b.HasIndex("ActedBy")
                        .HasDatabaseName("ix_workflow_step_acted_by");

                    b.HasIndex("AssignedUserId")
                        .HasDatabaseName("ix_workflow_step_assigned_user_id");

                    b.HasIndex("WorkflowInstanceId")
                        .HasDatabaseName("ix_workflow_step_workflow_instance_id");

                    b.ToTable("workflow_step", (string)null);
                });

            modelBuilder.Entity("Simando.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_app_user");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Simando.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claim_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Simando.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_login_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Simando.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_token_asp_net_users_user_id");
                });

            modelBuilder.Entity("Simando.Domain.Audit.StatusEvent", b =>
                {
                    b.HasOne("Simando.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_status_event_app_user_actor_id");

                    b.HasOne("Simando.Domain.Directory.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_status_event_company_company_id");

                    b.HasOne("Simando.Domain.Workflow.WorkflowStep", null)
                        .WithMany()
                        .HasForeignKey("WorkflowStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_status_event_workflow_steps_workflow_step_id");
                });

            modelBuilder.Entity("Simando.Domain.Directory.Company", b =>
                {
                    b.HasOne("Simando.Domain.Organisation.Area", null)
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_company_area_area_id");

                    b.HasOne("Simando.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_company_app_user_created_by");

                    b.HasOne("Simando.Domain.MasterData.IndustryType", null)
                        .WithMany()
                        .HasForeignKey("IndustryTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_company_industry_types_industry_type_id");

                    b.HasOne("Simando.Domain.Geography.Village", null)
                        .WithMany()
                        .HasForeignKey("VillageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_company_villages_village_id");
                });

            modelBuilder.Entity("Simando.Domain.Directory.CompanyContact", b =>
                {
                    b.HasOne("Simando.Domain.Directory.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_contact_company_company_id");
                });

            modelBuilder.Entity("Simando.Domain.Directory.Plotting", b =>
                {
                    b.HasOne("Simando.Domain.Directory.Company", null)
                        .WithOne()
                        .HasForeignKey("Simando.Domain.Directory.Plotting", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plotting_company_company_id");

                    b.HasOne("Simando.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("SalesUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plotting_app_user_sales_user_id");
                });

            modelBuilder.Entity("Simando.Domain.Geography.District", b =>
                {
                    b.HasOne("Simando.Domain.Geography.Regency", null)
                        .WithMany()
                        .HasForeignKey("RegencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_district_regencies_regency_id");
                });

            modelBuilder.Entity("Simando.Domain.Geography.Regency", b =>
                {
                    b.HasOne("Simando.Domain.Geography.Province", null)
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_regency_province_province_id");
                });

            modelBuilder.Entity("Simando.Domain.Geography.Village", b =>
                {
                    b.HasOne("Simando.Domain.Geography.District", null)
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_village_district_district_id");
                });

            modelBuilder.Entity("Simando.Domain.MasterData.UnitSetMember", b =>
                {
                    b.HasOne("Simando.Domain.MasterData.UnitOfMeasure", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_unit_set_member_unit_of_measure_unit_id");
                });

            modelBuilder.Entity("Simando.Domain.Notifications.Notification", b =>
                {
                    b.HasOne("Simando.Domain.Directory.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notification_company_company_id");

                    b.HasOne("Simando.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notification_app_user_recipient_user_id");
                });

            modelBuilder.Entity("Simando.Domain.Organisation.Area", b =>
                {
                    b.HasOne("Simando.Domain.Organisation.Region", null)
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_area_regions_region_id");
                });

            modelBuilder.Entity("Simando.Domain.Security.RoleAssignment", b =>
                {
                    b.HasOne("Simando.Domain.Organisation.Area", null)
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_role_assignment_area_area_id");

                    b.HasOne("Simando.Domain.Organisation.Region", null)
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_role_assignment_region_region_id");

                    b.HasOne("Simando.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_assignment_app_user_user_id");
                });

            modelBuilder.Entity("Simando.Domain.Workflow.WorkflowInstance", b =>
                {
                    b.HasOne("Simando.Domain.Directory.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_instance_company_company_id");
                });

            modelBuilder.Entity("Simando.Domain.Workflow.WorkflowStep", b =>
                {
                    b.HasOne("Simando.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ActedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_workflow_step_app_user_acted_by");

                    b.HasOne("Simando.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_workflow_step_app_user_assigned_user_id");

                    b.HasOne("Simando.Domain.Workflow.WorkflowInstance", null)
                        .WithMany()
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_step_workflow_instance_workflow_instance_id");
                });
#pragma warning restore 612, 618
        }
    }
}
