/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/attachments/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CurrentUserDto"];
                        "application/json": components["schemas"]["CurrentUserDto"];
                        "text/json": components["schemas"]["CurrentUserDto"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Locked */
                423: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CurrentUserDto"];
                        "application/json": components["schemas"]["CurrentUserDto"];
                        "text/json": components["schemas"]["CurrentUserDto"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordRequest"];
                    "text/json": components["schemas"]["ChangePasswordRequest"];
                    "application/*+json": components["schemas"]["ChangePasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CurrentUserDto"];
                        "application/json": components["schemas"]["CurrentUserDto"];
                        "text/json": components["schemas"]["CurrentUserDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number | string;
                    pageSize?: number | string;
                    stage?: number | string;
                    industryTypeId?: string;
                    searchTerm?: string;
                    provinceId?: string;
                    regencyId?: string;
                    districtId?: string;
                    villageId?: string;
                    posisiPelanggan?: components["schemas"]["PosisiPelanggan"];
                    kawasan?: components["schemas"]["Kawasan"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResultOfCompanyListItem"];
                        "application/json": components["schemas"]["PagedResultOfCompanyListItem"];
                        "text/json": components["schemas"]["PagedResultOfCompanyListItem"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCompanyRequest"];
                    "text/json": components["schemas"]["CreateCompanyRequest"];
                    "application/*+json": components["schemas"]["CreateCompanyRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateCompanyResult"];
                        "application/json": components["schemas"]["CreateCompanyResult"];
                        "text/json": components["schemas"]["CreateCompanyResult"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CompanyRecordDto"];
                        "application/json": components["schemas"]["CompanyRecordDto"];
                        "text/json": components["schemas"]["CompanyRecordDto"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateCompanyRequest"];
                    "text/json": components["schemas"]["UpdateCompanyRequest"];
                    "application/*+json": components["schemas"]["UpdateCompanyRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{id}/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ContactDetail"][];
                        "application/json": components["schemas"]["ContactDetail"][];
                        "text/json": components["schemas"]["ContactDetail"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SaveContactRequest"];
                    "text/json": components["schemas"]["SaveContactRequest"];
                    "application/*+json": components["schemas"]["SaveContactRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{id}/contacts/{contactId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    contactId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SaveContactRequest"];
                    "text/json": components["schemas"]["SaveContactRequest"];
                    "application/*+json": components["schemas"]["SaveContactRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    contactId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{id}/plotting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PlottingDetail"];
                        "application/json": components["schemas"]["PlottingDetail"];
                        "text/json": components["schemas"]["PlottingDetail"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SavePlottingRequest"];
                    "text/json": components["schemas"]["SavePlottingRequest"];
                    "application/*+json": components["schemas"]["SavePlottingRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{id}/promote-to-prospek": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{id}/location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateLocationRequest"];
                    "text/json": components["schemas"]["UpdateLocationRequest"];
                    "application/*+json": components["schemas"]["UpdateLocationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TimelineEntry"][];
                        "application/json": components["schemas"]["TimelineEntry"][];
                        "text/json": components["schemas"]["TimelineEntry"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/map-pins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CompanyMapPinDto"][];
                        "application/json": components["schemas"]["CompanyMapPinDto"][];
                        "text/json": components["schemas"]["CompanyMapPinDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/company/{companyId}/kk0": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    companyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/company/{companyId}/a1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    companyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/company/{companyId}/nol-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    companyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/company/{companyId}/evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    companyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/company/{companyId}/nol-issuance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    companyId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geography/provinces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GeographyOption"][];
                        "application/json": components["schemas"]["GeographyOption"][];
                        "text/json": components["schemas"]["GeographyOption"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geography/regencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    provinceId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GeographyOption"][];
                        "application/json": components["schemas"]["GeographyOption"][];
                        "text/json": components["schemas"]["GeographyOption"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geography/districts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    regencyId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GeographyOption"][];
                        "application/json": components["schemas"]["GeographyOption"][];
                        "text/json": components["schemas"]["GeographyOption"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geography/villages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    districtId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GeographyOption"][];
                        "application/json": components["schemas"]["GeographyOption"][];
                        "text/json": components["schemas"]["GeographyOption"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/master/industry-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["IndustryTypeDto"][];
                        "application/json": components["schemas"]["IndustryTypeDto"][];
                        "text/json": components["schemas"]["IndustryTypeDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/master/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AreaDto"][];
                        "application/json": components["schemas"]["AreaDto"][];
                        "text/json": components["schemas"]["AreaDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/master/sales-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SalesUserDto"][];
                        "application/json": components["schemas"]["SalesUserDto"][];
                        "text/json": components["schemas"]["SalesUserDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/export/funnel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/export/gas-demand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/export/survey-productivity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/export/nol-outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/export/directory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    includePii?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {unknown} */
        AccessScope: "Area" | "Region" | "All";
        AreaDto: {
            /** Format: uuid */
            id: string;
            name: string;
            code: string;
            /** Format: uuid */
            regionId: string;
            regionName: string;
        };
        /** @enum {unknown} */
        Capability: "ViewCompanyRecords" | "CreateCompany" | "EditStages1To3" | "SoftDeleteCompany" | "DropMovePin" | "EditSurvey" | "EditA1" | "SignUploadSignedA1" | "EditNolRequest" | "EditEvaluation" | "ProduceResumeEvaluasi" | "RecordFeedCheckpoint" | "UploadAttachments" | "DownloadAttachments" | "GenerateDocuments" | "SubmitForApproval" | "ActOnApprovalStep" | "IssueNolRl" | "SetApprovedTerms" | "ChooseReviewers" | "ReassignWorkflowStep" | "ViewTimeline" | "ViewDashboardFunnel" | "ViewAgeingReport" | "ExportExcel" | "ExportContactDataPii" | "ManageMasterData" | "BreakGlassRecordRead" | "AssignRoles" | "ViewBreakGlassActivity";
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        CompanyListItem: {
            /** Format: uuid */
            id: string;
            nomor: string;
            namaPerusahaan: string;
            industryTypeName: string;
            locationLabel: string;
            /** Format: uint8 */
            currentStage: number | string;
            status: components["schemas"]["RecordStatus"];
            /** Format: uuid */
            salesUserId: null | string;
            salesUserName: null | string;
            posisiPelanggan: null | components["schemas"]["PosisiPelanggan"];
            kawasan: null | components["schemas"]["Kawasan"];
            /** Format: double */
            latitude: null | number | string;
            /** Format: double */
            longitude: null | number | string;
        };
        CompanyMapPinDto: {
            /** Format: uuid */
            id: string;
            nomor: string;
            namaPerusahaan: string;
            /** Format: double */
            latitude: number | string;
            /** Format: double */
            longitude: number | string;
            /** Format: uint8 */
            currentStage: number | string;
            status: components["schemas"]["RecordStatus"];
            industryTypeName: string;
            locationLabel: string;
            posisiPelanggan: null | components["schemas"]["PosisiPelanggan"];
            kawasan: null | components["schemas"]["Kawasan"];
            salesUserName: null | string;
        };
        CompanyRecordDto: {
            /** Format: uuid */
            id: string;
            nomor: string;
            namaPerusahaan: string;
            website: null | string;
            alamat: string;
            /** Format: uuid */
            villageId: string;
            villageName: string;
            /** Format: uuid */
            districtId: string;
            districtName: string;
            /** Format: uuid */
            regencyId: string;
            regencyName: string;
            /** Format: uuid */
            provinceId: string;
            provinceName: string;
            locationLabel: string;
            /** Format: uuid */
            industryTypeId: string;
            industryTypeName: string;
            npwp: null | string;
            email: null | string;
            kodePos: null | string;
            telp: null | string;
            /** Format: uuid */
            areaId: string;
            areaName: string;
            /** Format: uuid */
            regionId: string;
            regionName: string;
            /** Format: uint8 */
            currentStage: number | string;
            status: components["schemas"]["RecordStatus"];
            /** Format: uuid */
            createdBy: string;
            salesRepName: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: null | string;
            /** Format: double */
            latitude: null | number | string;
            /** Format: double */
            longitude: null | number | string;
            holderLabel: null | string;
            holderName: null | string;
            /** Format: date-time */
            statusSince: string;
            /** Format: uuid */
            currentStepId: null | string;
            currentStepKind: null | components["schemas"]["WorkflowStepKind"];
            /** Format: uuid */
            workflowInstanceId: null | string;
            canSubmit: boolean;
            canAct: boolean;
            canChooseReviewers: boolean;
            contacts: components["schemas"]["ContactDetail"][];
        };
        ContactDetail: {
            /** Format: uuid */
            id: string;
            nama: string;
            jabatan: string;
            email: null | string;
            noHp: null | string;
            linkedIn: null | string;
            instagram: null | string;
            facebook: null | string;
            isPrimary: boolean;
            /** Format: int16 */
            sortOrder: number | string;
        };
        CreateCompanyRequest: {
            namaPerusahaan: string;
            website: null | string;
            /** Format: uuid */
            villageId: string;
            alamat: string;
            /** Format: double */
            latitude: number | string;
            /** Format: double */
            longitude: number | string;
            /** Format: uuid */
            industryTypeId: string;
            /** Format: uuid */
            areaId: string;
            email: null | string;
            kodePos: null | string;
            telp: null | string;
            npwp: null | string;
        };
        CreateCompanyResult: {
            /** Format: uuid */
            companyId: string;
            nomor: string;
        };
        CurrentUserDto: {
            /** Format: uuid */
            id: string;
            username: string;
            email: string;
            fullName: string;
            scope: components["schemas"]["AccessScope"];
            /** Format: uuid */
            areaId: null | string;
            /** Format: uuid */
            regionId: null | string;
            roles: components["schemas"]["Role"][];
            capabilities: components["schemas"]["Capability"][];
            mustChangePassword: boolean;
        };
        GeographyOption: {
            /** Format: uuid */
            id: string;
            name: string;
            bpsCode: string;
        };
        IndustryTypeDto: {
            /** Format: uuid */
            id: string;
            name: string;
            contohProduk: null | string;
        };
        /** @enum {unknown} */
        Kawasan: "KawasanIndustri" | "NonKawasanIndustri" | null;
        LoginRequest: {
            username: string;
            password: string;
        };
        PagedResultOfCompanyListItem: {
            items: components["schemas"]["CompanyListItem"][];
            /** Format: int32 */
            totalCount: number | string;
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
        };
        PlottingDetail: {
            /** Format: uuid */
            companyId: string;
            /** Format: uuid */
            salesUserId: null | string;
            salesUserName: null | string;
            posisiPelanggan: null | components["schemas"]["PosisiPelanggan"];
            kawasan: null | components["schemas"]["Kawasan"];
        };
        /** @enum {unknown} */
        PosisiPelanggan: "Pengembangan" | "JalurExisting" | null;
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        /** @enum {unknown} */
        RecordStatus: "Draft" | "AreaHead" | "RegionalAdmin" | "Reviewer1" | "Reviewer2" | "Reviewer3" | "Approval" | "Rejected" | "IssuedNol" | "IssuedRl" | "Discontinued";
        /** @enum {unknown} */
        Role: "SalesArea" | "AreaHead" | "RegionalAdmin" | "Reviewer" | "DivisionHead" | "SystemAdmin";
        SalesUserDto: {
            /** Format: uuid */
            id: string;
            fullName: string;
            username: string;
            email: string;
        };
        SaveContactRequest: {
            nama: string;
            jabatan: string;
            email: null | string;
            noHp: null | string;
            linkedIn: null | string;
            instagram: null | string;
            facebook: null | string;
            isPrimary: boolean;
        };
        SavePlottingRequest: {
            /** Format: uuid */
            salesUserId: string;
            posisiPelanggan: components["schemas"]["PosisiPelanggan"];
            kawasan: components["schemas"]["Kawasan"];
        };
        /** @enum {unknown} */
        StatusEventAction: "Create" | "Save" | "Submit" | "Setuju" | "Revisi" | "Tolak" | "Issue" | "BreakGlass" | "Reassign" | "Rework" | "Discontinue";
        TimelineEntry: {
            /** Format: uuid */
            id: string;
            action: components["schemas"]["StatusEventAction"];
            toStatus: components["schemas"]["RecordStatus"];
            roleLabel: string;
            actorName: string;
            comment: null | string;
            /** Format: date-time */
            occurredAt: string;
        };
        UpdateCompanyRequest: {
            namaPerusahaan: string;
            website: null | string;
            /** Format: uuid */
            villageId: string;
            alamat: string;
            /** Format: double */
            latitude: number | string;
            /** Format: double */
            longitude: number | string;
            /** Format: uuid */
            industryTypeId: string;
            email: null | string;
            kodePos: null | string;
            telp: null | string;
            npwp: null | string;
        };
        UpdateLocationRequest: {
            /** Format: double */
            latitude: number | string;
            /** Format: double */
            longitude: number | string;
        };
        /** @enum {unknown} */
        WorkflowStepKind: "AreaHead" | "RegionalAdmin" | "Reviewer1" | "Reviewer2" | "Reviewer3" | "DivisionHead" | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
