/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api/auth/login": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["LoginRequest"];
				};
			};
			responses: {
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["CurrentUserDto"];
					};
				};
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/problem+json": components["schemas"]["ProblemDetails"];
					};
				};
				423: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/problem+json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/auth/logout": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/auth/me": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["CurrentUserDto"];
					};
				};
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/auth/change-password": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["ChangePasswordRequest"];
				};
			};
			responses: {
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["CurrentUserDto"];
					};
				};
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/problem+json": components["schemas"]["ProblemDetails"];
					};
				};
				401: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}

export type webhooks = Record<string, never>;

export interface components {
	schemas: {
		AccessScope: "All" | "Region" | "Area";
		Role:
			| "SalesArea"
			| "AreaHead"
			| "RegionalAdmin"
			| "Reviewer"
			| "DivisionHead"
			| "SystemAdmin";
		Capability:
			| "ViewCompanyRecords"
			| "CreateCompany"
			| "EditStages1To3"
			| "SoftDeleteCompany"
			| "DropMovePin"
			| "EditSurvey"
			| "EditA1"
			| "SignUploadSignedA1"
			| "EditNolRequest"
			| "EditEvaluation"
			| "ProduceResumeEvaluasi"
			| "RecordFeedCheckpoint"
			| "UploadAttachments"
			| "DownloadAttachments"
			| "GenerateDocuments"
			| "SubmitForApproval"
			| "ActOnApprovalStep"
			| "IssueNolRl"
			| "SetApprovedTerms"
			| "ChooseReviewers"
			| "ReassignWorkflowStep"
			| "ViewTimeline"
			| "ViewDashboardFunnel"
			| "ViewAgeingReport"
			| "ExportExcel"
			| "ExportContactDataPii"
			| "ManageMasterData"
			| "BreakGlassRecordRead"
			| "AssignRoles"
			| "ViewBreakGlassActivity";
		ChangePasswordRequest: {
			currentPassword: string;
			newPassword: string;
		};
		CurrentUserDto: {
			/** Format: uuid */
			id: string;
			username: string;
			email: string;
			fullName: string;
			scope: components["schemas"]["AccessScope"];
			/** Format: uuid */
			areaId?: string | null;
			/** Format: uuid */
			regionId?: string | null;
			roles: components["schemas"]["Role"][];
			capabilities: components["schemas"]["Capability"][];
			mustChangePassword: boolean;
		};
		LoginRequest: {
			username: string;
			password: string;
		};
		ProblemDetails: {
			type?: string | null;
			title?: string | null;
			/** Format: int32 */
			status?: number | null;
			detail?: string | null;
			instance?: string | null;
			[key: string]: unknown;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}

export type $defs = Record<string, never>;

export type operations = Record<string, never>;
