/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthMapRouteImport } from './routes/_auth/map'
import { Route as AuthTasksRouteImport } from './routes/_auth/tasks'
import { Route as AuthDirectoryIndexRouteImport } from './routes/_auth/directory/index'
import { Route as AuthDirectoryCompanyIdRouteImport } from './routes/_auth/directory/$companyId'
import { Route as AuthDirectoryNewRouteImport } from './routes/_auth/directory/new'
import { Route as AuthTasksIndexRouteImport } from './routes/_auth/tasks/index'
import { Route as AuthTasksBlockedRouteImport } from './routes/_auth/tasks/blocked'
import { Route as AuthTasksHistoryRouteImport } from './routes/_auth/tasks/history'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMapRoute = AuthMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTasksRoute = AuthTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDirectoryIndexRoute = AuthDirectoryIndexRouteImport.update({
  id: '/directory/',
  path: '/directory/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDirectoryCompanyIdRoute = AuthDirectoryCompanyIdRouteImport.update({
  id: '/directory/$companyId',
  path: '/directory/$companyId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDirectoryNewRoute = AuthDirectoryNewRouteImport.update({
  id: '/directory/new',
  path: '/directory/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTasksIndexRoute = AuthTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthTasksRoute,
} as any)
const AuthTasksBlockedRoute = AuthTasksBlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => AuthTasksRoute,
} as any)
const AuthTasksHistoryRoute = AuthTasksHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthTasksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/change-password': typeof ChangePasswordRoute
  '/sign-in': typeof SignInRoute
  '/map': typeof AuthMapRoute
  '/tasks': typeof AuthTasksRouteWithChildren
  '/directory/$companyId': typeof AuthDirectoryCompanyIdRoute
  '/directory/new': typeof AuthDirectoryNewRoute
  '/tasks/blocked': typeof AuthTasksBlockedRoute
  '/tasks/history': typeof AuthTasksHistoryRoute
  '/directory/': typeof AuthDirectoryIndexRoute
  '/tasks/': typeof AuthTasksIndexRoute
}
export interface FileRoutesByTo {
  '/access-denied': typeof AccessDeniedRoute
  '/change-password': typeof ChangePasswordRoute
  '/sign-in': typeof SignInRoute
  '/map': typeof AuthMapRoute
  '/': typeof AuthIndexRoute
  '/directory/$companyId': typeof AuthDirectoryCompanyIdRoute
  '/directory/new': typeof AuthDirectoryNewRoute
  '/tasks/blocked': typeof AuthTasksBlockedRoute
  '/tasks/history': typeof AuthTasksHistoryRoute
  '/directory': typeof AuthDirectoryIndexRoute
  '/tasks': typeof AuthTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/change-password': typeof ChangePasswordRoute
  '/sign-in': typeof SignInRoute
  '/_auth/map': typeof AuthMapRoute
  '/_auth/tasks': typeof AuthTasksRouteWithChildren
  '/_auth/': typeof AuthIndexRoute
  '/_auth/directory/$companyId': typeof AuthDirectoryCompanyIdRoute
  '/_auth/directory/new': typeof AuthDirectoryNewRoute
  '/_auth/tasks/blocked': typeof AuthTasksBlockedRoute
  '/_auth/tasks/history': typeof AuthTasksHistoryRoute
  '/_auth/directory/': typeof AuthDirectoryIndexRoute
  '/_auth/tasks/': typeof AuthTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/change-password'
    | '/sign-in'
    | '/map'
    | '/tasks'
    | '/directory/$companyId'
    | '/directory/new'
    | '/tasks/blocked'
    | '/tasks/history'
    | '/directory/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/access-denied'
    | '/change-password'
    | '/sign-in'
    | '/map'
    | '/'
    | '/directory/$companyId'
    | '/directory/new'
    | '/tasks/blocked'
    | '/tasks/history'
    | '/directory'
    | '/tasks'
  id:
    | '__root__'
    | '/_auth'
    | '/access-denied'
    | '/change-password'
    | '/sign-in'
    | '/_auth/map'
    | '/_auth/tasks'
    | '/_auth/'
    | '/_auth/directory/$companyId'
    | '/_auth/directory/new'
    | '/_auth/tasks/blocked'
    | '/_auth/tasks/history'
    | '/_auth/directory/'
    | '/_auth/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/map': {
      id: '/_auth/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthMapRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tasks': {
      id: '/_auth/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthTasksRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/directory/': {
      id: '/_auth/directory/'
      path: '/directory'
      fullPath: '/directory/'
      preLoaderRoute: typeof AuthDirectoryIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/directory/$companyId': {
      id: '/_auth/directory/$companyId'
      path: '/directory/$companyId'
      fullPath: '/directory/$companyId'
      preLoaderRoute: typeof AuthDirectoryCompanyIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/directory/new': {
      id: '/_auth/directory/new'
      path: '/directory/new'
      fullPath: '/directory/new'
      preLoaderRoute: typeof AuthDirectoryNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tasks/': {
      id: '/_auth/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthTasksIndexRouteImport
      parentRoute: typeof AuthTasksRoute
    }
    '/_auth/tasks/blocked': {
      id: '/_auth/tasks/blocked'
      path: '/blocked'
      fullPath: '/tasks/blocked'
      preLoaderRoute: typeof AuthTasksBlockedRouteImport
      parentRoute: typeof AuthTasksRoute
    }
    '/_auth/tasks/history': {
      id: '/_auth/tasks/history'
      path: '/history'
      fullPath: '/tasks/history'
      preLoaderRoute: typeof AuthTasksHistoryRouteImport
      parentRoute: typeof AuthTasksRoute
    }
  }
}

interface AuthTasksRouteChildren {
  AuthTasksBlockedRoute: typeof AuthTasksBlockedRoute
  AuthTasksHistoryRoute: typeof AuthTasksHistoryRoute
  AuthTasksIndexRoute: typeof AuthTasksIndexRoute
}

const AuthTasksRouteChildren: AuthTasksRouteChildren = {
  AuthTasksBlockedRoute: AuthTasksBlockedRoute,
  AuthTasksHistoryRoute: AuthTasksHistoryRoute,
  AuthTasksIndexRoute: AuthTasksIndexRoute,
}

const AuthTasksRouteWithChildren = AuthTasksRoute._addFileChildren(
  AuthTasksRouteChildren,
)

interface AuthRouteChildren {
  AuthMapRoute: typeof AuthMapRoute
  AuthTasksRoute: typeof AuthTasksRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
  AuthDirectoryCompanyIdRoute: typeof AuthDirectoryCompanyIdRoute
  AuthDirectoryNewRoute: typeof AuthDirectoryNewRoute
  AuthDirectoryIndexRoute: typeof AuthDirectoryIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthMapRoute: AuthMapRoute,
  AuthTasksRoute: AuthTasksRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
  AuthDirectoryCompanyIdRoute: AuthDirectoryCompanyIdRoute,
  AuthDirectoryNewRoute: AuthDirectoryNewRoute,
  AuthDirectoryIndexRoute: AuthDirectoryIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
