/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthMapRouteImport } from './routes/_auth/map'
import { Route as AuthTasksRouteImport } from './routes/_auth/tasks'
import { Route as AuthAdminBreakGlassRouteImport } from './routes/_auth/admin/break-glass'
import { Route as AuthAdminStuckStepsRouteImport } from './routes/_auth/admin/stuck-steps'
import { Route as AuthDirectoryIndexRouteImport } from './routes/_auth/directory/index'
import { Route as AuthDirectoryCompanyIdRouteImport } from './routes/_auth/directory/$companyId'
import { Route as AuthDirectoryNewRouteImport } from './routes/_auth/directory/new'
import { Route as AuthMasterCountriesRouteImport } from './routes/_auth/master/countries'
import { Route as AuthMasterFuelTypesRouteImport } from './routes/_auth/master/fuel-types'
import { Route as AuthMasterIndustryTypesRouteImport } from './routes/_auth/master/industry-types'
import { Route as AuthMasterMeterSizesRouteImport } from './routes/_auth/master/meter-sizes'
import { Route as AuthMasterMrsSpecsRouteImport } from './routes/_auth/master/mrs-specs'
import { Route as AuthMasterOrganisationRouteImport } from './routes/_auth/master/organisation'
import { Route as AuthMasterReasonCategoriesRouteImport } from './routes/_auth/master/reason-categories'
import { Route as AuthMasterReferenceDocumentsRouteImport } from './routes/_auth/master/reference-documents'
import { Route as AuthMasterSegmentsRouteImport } from './routes/_auth/master/segments'
import { Route as AuthMasterUnitsRouteImport } from './routes/_auth/master/units'
import { Route as AuthMasterUsersRouteImport } from './routes/_auth/master/users'
import { Route as AuthReportsIndexRouteImport } from './routes/_auth/reports/index'
import { Route as AuthReportsAgeingRouteImport } from './routes/_auth/reports/ageing'
import { Route as AuthReportsFunnelRouteImport } from './routes/_auth/reports/funnel'
import { Route as AuthReportsGasDemandRouteImport } from './routes/_auth/reports/gas-demand'
import { Route as AuthReportsNolOutcomesRouteImport } from './routes/_auth/reports/nol-outcomes'
import { Route as AuthReportsSurveyProductivityRouteImport } from './routes/_auth/reports/survey-productivity'
import { Route as AuthTasksIndexRouteImport } from './routes/_auth/tasks/index'
import { Route as AuthTasksBlockedRouteImport } from './routes/_auth/tasks/blocked'
import { Route as AuthTasksHistoryRouteImport } from './routes/_auth/tasks/history'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMapRoute = AuthMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTasksRoute = AuthTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminBreakGlassRoute = AuthAdminBreakGlassRouteImport.update({
  id: '/admin/break-glass',
  path: '/admin/break-glass',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminStuckStepsRoute = AuthAdminStuckStepsRouteImport.update({
  id: '/admin/stuck-steps',
  path: '/admin/stuck-steps',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDirectoryIndexRoute = AuthDirectoryIndexRouteImport.update({
  id: '/directory/',
  path: '/directory/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDirectoryCompanyIdRoute = AuthDirectoryCompanyIdRouteImport.update({
  id: '/directory/$companyId',
  path: '/directory/$companyId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDirectoryNewRoute = AuthDirectoryNewRouteImport.update({
  id: '/directory/new',
  path: '/directory/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMasterCountriesRoute = AuthMasterCountriesRouteImport.update({
  id: '/master/countries',
  path: '/master/countries',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMasterFuelTypesRoute = AuthMasterFuelTypesRouteImport.update({
  id: '/master/fuel-types',
  path: '/master/fuel-types',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMasterIndustryTypesRoute = AuthMasterIndustryTypesRouteImport.update({
  id: '/master/industry-types',
  path: '/master/industry-types',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMasterMeterSizesRoute = AuthMasterMeterSizesRouteImport.update({
  id: '/master/meter-sizes',
  path: '/master/meter-sizes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMasterMrsSpecsRoute = AuthMasterMrsSpecsRouteImport.update({
  id: '/master/mrs-specs',
  path: '/master/mrs-specs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMasterOrganisationRoute = AuthMasterOrganisationRouteImport.update({
  id: '/master/organisation',
  path: '/master/organisation',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMasterReasonCategoriesRoute =
  AuthMasterReasonCategoriesRouteImport.update({
    id: '/master/reason-categories',
    path: '/master/reason-categories',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthMasterReferenceDocumentsRoute =
  AuthMasterReferenceDocumentsRouteImport.update({
    id: '/master/reference-documents',
    path: '/master/reference-documents',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthMasterSegmentsRoute = AuthMasterSegmentsRouteImport.update({
  id: '/master/segments',
  path: '/master/segments',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMasterUnitsRoute = AuthMasterUnitsRouteImport.update({
  id: '/master/units',
  path: '/master/units',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMasterUsersRoute = AuthMasterUsersRouteImport.update({
  id: '/master/users',
  path: '/master/users',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReportsIndexRoute = AuthReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReportsAgeingRoute = AuthReportsAgeingRouteImport.update({
  id: '/reports/ageing',
  path: '/reports/ageing',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReportsFunnelRoute = AuthReportsFunnelRouteImport.update({
  id: '/reports/funnel',
  path: '/reports/funnel',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReportsGasDemandRoute = AuthReportsGasDemandRouteImport.update({
  id: '/reports/gas-demand',
  path: '/reports/gas-demand',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReportsNolOutcomesRoute = AuthReportsNolOutcomesRouteImport.update({
  id: '/reports/nol-outcomes',
  path: '/reports/nol-outcomes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReportsSurveyProductivityRoute =
  AuthReportsSurveyProductivityRouteImport.update({
    id: '/reports/survey-productivity',
    path: '/reports/survey-productivity',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthTasksIndexRoute = AuthTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthTasksRoute,
} as any)
const AuthTasksBlockedRoute = AuthTasksBlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => AuthTasksRoute,
} as any)
const AuthTasksHistoryRoute = AuthTasksHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthTasksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/change-password': typeof ChangePasswordRoute
  '/sign-in': typeof SignInRoute
  '/map': typeof AuthMapRoute
  '/tasks': typeof AuthTasksRouteWithChildren
  '/admin/break-glass': typeof AuthAdminBreakGlassRoute
  '/admin/stuck-steps': typeof AuthAdminStuckStepsRoute
  '/directory/$companyId': typeof AuthDirectoryCompanyIdRoute
  '/directory/new': typeof AuthDirectoryNewRoute
  '/master/countries': typeof AuthMasterCountriesRoute
  '/master/fuel-types': typeof AuthMasterFuelTypesRoute
  '/master/industry-types': typeof AuthMasterIndustryTypesRoute
  '/master/meter-sizes': typeof AuthMasterMeterSizesRoute
  '/master/mrs-specs': typeof AuthMasterMrsSpecsRoute
  '/master/organisation': typeof AuthMasterOrganisationRoute
  '/master/reason-categories': typeof AuthMasterReasonCategoriesRoute
  '/master/reference-documents': typeof AuthMasterReferenceDocumentsRoute
  '/master/segments': typeof AuthMasterSegmentsRoute
  '/master/units': typeof AuthMasterUnitsRoute
  '/master/users': typeof AuthMasterUsersRoute
  '/reports/ageing': typeof AuthReportsAgeingRoute
  '/reports/funnel': typeof AuthReportsFunnelRoute
  '/reports/gas-demand': typeof AuthReportsGasDemandRoute
  '/reports/nol-outcomes': typeof AuthReportsNolOutcomesRoute
  '/reports/survey-productivity': typeof AuthReportsSurveyProductivityRoute
  '/tasks/blocked': typeof AuthTasksBlockedRoute
  '/tasks/history': typeof AuthTasksHistoryRoute
  '/directory/': typeof AuthDirectoryIndexRoute
  '/reports/': typeof AuthReportsIndexRoute
  '/tasks/': typeof AuthTasksIndexRoute
}
export interface FileRoutesByTo {
  '/access-denied': typeof AccessDeniedRoute
  '/change-password': typeof ChangePasswordRoute
  '/sign-in': typeof SignInRoute
  '/map': typeof AuthMapRoute
  '/': typeof AuthIndexRoute
  '/admin/break-glass': typeof AuthAdminBreakGlassRoute
  '/admin/stuck-steps': typeof AuthAdminStuckStepsRoute
  '/directory/$companyId': typeof AuthDirectoryCompanyIdRoute
  '/directory/new': typeof AuthDirectoryNewRoute
  '/master/countries': typeof AuthMasterCountriesRoute
  '/master/fuel-types': typeof AuthMasterFuelTypesRoute
  '/master/industry-types': typeof AuthMasterIndustryTypesRoute
  '/master/meter-sizes': typeof AuthMasterMeterSizesRoute
  '/master/mrs-specs': typeof AuthMasterMrsSpecsRoute
  '/master/organisation': typeof AuthMasterOrganisationRoute
  '/master/reason-categories': typeof AuthMasterReasonCategoriesRoute
  '/master/reference-documents': typeof AuthMasterReferenceDocumentsRoute
  '/master/segments': typeof AuthMasterSegmentsRoute
  '/master/units': typeof AuthMasterUnitsRoute
  '/master/users': typeof AuthMasterUsersRoute
  '/reports/ageing': typeof AuthReportsAgeingRoute
  '/reports/funnel': typeof AuthReportsFunnelRoute
  '/reports/gas-demand': typeof AuthReportsGasDemandRoute
  '/reports/nol-outcomes': typeof AuthReportsNolOutcomesRoute
  '/reports/survey-productivity': typeof AuthReportsSurveyProductivityRoute
  '/tasks/blocked': typeof AuthTasksBlockedRoute
  '/tasks/history': typeof AuthTasksHistoryRoute
  '/directory': typeof AuthDirectoryIndexRoute
  '/reports': typeof AuthReportsIndexRoute
  '/tasks': typeof AuthTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/change-password': typeof ChangePasswordRoute
  '/sign-in': typeof SignInRoute
  '/_auth/map': typeof AuthMapRoute
  '/_auth/tasks': typeof AuthTasksRouteWithChildren
  '/_auth/': typeof AuthIndexRoute
  '/_auth/admin/break-glass': typeof AuthAdminBreakGlassRoute
  '/_auth/admin/stuck-steps': typeof AuthAdminStuckStepsRoute
  '/_auth/directory/$companyId': typeof AuthDirectoryCompanyIdRoute
  '/_auth/directory/new': typeof AuthDirectoryNewRoute
  '/_auth/master/countries': typeof AuthMasterCountriesRoute
  '/_auth/master/fuel-types': typeof AuthMasterFuelTypesRoute
  '/_auth/master/industry-types': typeof AuthMasterIndustryTypesRoute
  '/_auth/master/meter-sizes': typeof AuthMasterMeterSizesRoute
  '/_auth/master/mrs-specs': typeof AuthMasterMrsSpecsRoute
  '/_auth/master/organisation': typeof AuthMasterOrganisationRoute
  '/_auth/master/reason-categories': typeof AuthMasterReasonCategoriesRoute
  '/_auth/master/reference-documents': typeof AuthMasterReferenceDocumentsRoute
  '/_auth/master/segments': typeof AuthMasterSegmentsRoute
  '/_auth/master/units': typeof AuthMasterUnitsRoute
  '/_auth/master/users': typeof AuthMasterUsersRoute
  '/_auth/reports/ageing': typeof AuthReportsAgeingRoute
  '/_auth/reports/funnel': typeof AuthReportsFunnelRoute
  '/_auth/reports/gas-demand': typeof AuthReportsGasDemandRoute
  '/_auth/reports/nol-outcomes': typeof AuthReportsNolOutcomesRoute
  '/_auth/reports/survey-productivity': typeof AuthReportsSurveyProductivityRoute
  '/_auth/tasks/blocked': typeof AuthTasksBlockedRoute
  '/_auth/tasks/history': typeof AuthTasksHistoryRoute
  '/_auth/directory/': typeof AuthDirectoryIndexRoute
  '/_auth/reports/': typeof AuthReportsIndexRoute
  '/_auth/tasks/': typeof AuthTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/change-password'
    | '/sign-in'
    | '/map'
    | '/tasks'
    | '/admin/break-glass'
    | '/admin/stuck-steps'
    | '/directory/$companyId'
    | '/directory/new'
    | '/master/countries'
    | '/master/fuel-types'
    | '/master/industry-types'
    | '/master/meter-sizes'
    | '/master/mrs-specs'
    | '/master/organisation'
    | '/master/reason-categories'
    | '/master/reference-documents'
    | '/master/segments'
    | '/master/units'
    | '/master/users'
    | '/reports/ageing'
    | '/reports/funnel'
    | '/reports/gas-demand'
    | '/reports/nol-outcomes'
    | '/reports/survey-productivity'
    | '/tasks/blocked'
    | '/tasks/history'
    | '/directory/'
    | '/reports/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/access-denied'
    | '/change-password'
    | '/sign-in'
    | '/map'
    | '/'
    | '/admin/break-glass'
    | '/admin/stuck-steps'
    | '/directory/$companyId'
    | '/directory/new'
    | '/master/countries'
    | '/master/fuel-types'
    | '/master/industry-types'
    | '/master/meter-sizes'
    | '/master/mrs-specs'
    | '/master/organisation'
    | '/master/reason-categories'
    | '/master/reference-documents'
    | '/master/segments'
    | '/master/units'
    | '/master/users'
    | '/reports/ageing'
    | '/reports/funnel'
    | '/reports/gas-demand'
    | '/reports/nol-outcomes'
    | '/reports/survey-productivity'
    | '/tasks/blocked'
    | '/tasks/history'
    | '/directory'
    | '/reports'
    | '/tasks'
  id:
    | '__root__'
    | '/_auth'
    | '/access-denied'
    | '/change-password'
    | '/sign-in'
    | '/_auth/map'
    | '/_auth/tasks'
    | '/_auth/'
    | '/_auth/admin/break-glass'
    | '/_auth/admin/stuck-steps'
    | '/_auth/directory/$companyId'
    | '/_auth/directory/new'
    | '/_auth/master/countries'
    | '/_auth/master/fuel-types'
    | '/_auth/master/industry-types'
    | '/_auth/master/meter-sizes'
    | '/_auth/master/mrs-specs'
    | '/_auth/master/organisation'
    | '/_auth/master/reason-categories'
    | '/_auth/master/reference-documents'
    | '/_auth/master/segments'
    | '/_auth/master/units'
    | '/_auth/master/users'
    | '/_auth/reports/ageing'
    | '/_auth/reports/funnel'
    | '/_auth/reports/gas-demand'
    | '/_auth/reports/nol-outcomes'
    | '/_auth/reports/survey-productivity'
    | '/_auth/tasks/blocked'
    | '/_auth/tasks/history'
    | '/_auth/directory/'
    | '/_auth/reports/'
    | '/_auth/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/map': {
      id: '/_auth/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthMapRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tasks': {
      id: '/_auth/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthTasksRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/break-glass': {
      id: '/_auth/admin/break-glass'
      path: '/admin/break-glass'
      fullPath: '/admin/break-glass'
      preLoaderRoute: typeof AuthAdminBreakGlassRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/stuck-steps': {
      id: '/_auth/admin/stuck-steps'
      path: '/admin/stuck-steps'
      fullPath: '/admin/stuck-steps'
      preLoaderRoute: typeof AuthAdminStuckStepsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/directory/': {
      id: '/_auth/directory/'
      path: '/directory'
      fullPath: '/directory/'
      preLoaderRoute: typeof AuthDirectoryIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/directory/$companyId': {
      id: '/_auth/directory/$companyId'
      path: '/directory/$companyId'
      fullPath: '/directory/$companyId'
      preLoaderRoute: typeof AuthDirectoryCompanyIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/directory/new': {
      id: '/_auth/directory/new'
      path: '/directory/new'
      fullPath: '/directory/new'
      preLoaderRoute: typeof AuthDirectoryNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/master/countries': {
      id: '/_auth/master/countries'
      path: '/master/countries'
      fullPath: '/master/countries'
      preLoaderRoute: typeof AuthMasterCountriesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/master/fuel-types': {
      id: '/_auth/master/fuel-types'
      path: '/master/fuel-types'
      fullPath: '/master/fuel-types'
      preLoaderRoute: typeof AuthMasterFuelTypesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/master/industry-types': {
      id: '/_auth/master/industry-types'
      path: '/master/industry-types'
      fullPath: '/master/industry-types'
      preLoaderRoute: typeof AuthMasterIndustryTypesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/master/meter-sizes': {
      id: '/_auth/master/meter-sizes'
      path: '/master/meter-sizes'
      fullPath: '/master/meter-sizes'
      preLoaderRoute: typeof AuthMasterMeterSizesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/master/mrs-specs': {
      id: '/_auth/master/mrs-specs'
      path: '/master/mrs-specs'
      fullPath: '/master/mrs-specs'
      preLoaderRoute: typeof AuthMasterMrsSpecsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/master/organisation': {
      id: '/_auth/master/organisation'
      path: '/master/organisation'
      fullPath: '/master/organisation'
      preLoaderRoute: typeof AuthMasterOrganisationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/master/reason-categories': {
      id: '/_auth/master/reason-categories'
      path: '/master/reason-categories'
      fullPath: '/master/reason-categories'
      preLoaderRoute: typeof AuthMasterReasonCategoriesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/master/reference-documents': {
      id: '/_auth/master/reference-documents'
      path: '/master/reference-documents'
      fullPath: '/master/reference-documents'
      preLoaderRoute: typeof AuthMasterReferenceDocumentsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/master/segments': {
      id: '/_auth/master/segments'
      path: '/master/segments'
      fullPath: '/master/segments'
      preLoaderRoute: typeof AuthMasterSegmentsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/master/units': {
      id: '/_auth/master/units'
      path: '/master/units'
      fullPath: '/master/units'
      preLoaderRoute: typeof AuthMasterUnitsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/master/users': {
      id: '/_auth/master/users'
      path: '/master/users'
      fullPath: '/master/users'
      preLoaderRoute: typeof AuthMasterUsersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports/': {
      id: '/_auth/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthReportsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports/ageing': {
      id: '/_auth/reports/ageing'
      path: '/reports/ageing'
      fullPath: '/reports/ageing'
      preLoaderRoute: typeof AuthReportsAgeingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports/funnel': {
      id: '/_auth/reports/funnel'
      path: '/reports/funnel'
      fullPath: '/reports/funnel'
      preLoaderRoute: typeof AuthReportsFunnelRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports/gas-demand': {
      id: '/_auth/reports/gas-demand'
      path: '/reports/gas-demand'
      fullPath: '/reports/gas-demand'
      preLoaderRoute: typeof AuthReportsGasDemandRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports/nol-outcomes': {
      id: '/_auth/reports/nol-outcomes'
      path: '/reports/nol-outcomes'
      fullPath: '/reports/nol-outcomes'
      preLoaderRoute: typeof AuthReportsNolOutcomesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports/survey-productivity': {
      id: '/_auth/reports/survey-productivity'
      path: '/reports/survey-productivity'
      fullPath: '/reports/survey-productivity'
      preLoaderRoute: typeof AuthReportsSurveyProductivityRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tasks/': {
      id: '/_auth/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthTasksIndexRouteImport
      parentRoute: typeof AuthTasksRoute
    }
    '/_auth/tasks/blocked': {
      id: '/_auth/tasks/blocked'
      path: '/blocked'
      fullPath: '/tasks/blocked'
      preLoaderRoute: typeof AuthTasksBlockedRouteImport
      parentRoute: typeof AuthTasksRoute
    }
    '/_auth/tasks/history': {
      id: '/_auth/tasks/history'
      path: '/history'
      fullPath: '/tasks/history'
      preLoaderRoute: typeof AuthTasksHistoryRouteImport
      parentRoute: typeof AuthTasksRoute
    }
  }
}

interface AuthTasksRouteChildren {
  AuthTasksBlockedRoute: typeof AuthTasksBlockedRoute
  AuthTasksHistoryRoute: typeof AuthTasksHistoryRoute
  AuthTasksIndexRoute: typeof AuthTasksIndexRoute
}

const AuthTasksRouteChildren: AuthTasksRouteChildren = {
  AuthTasksBlockedRoute: AuthTasksBlockedRoute,
  AuthTasksHistoryRoute: AuthTasksHistoryRoute,
  AuthTasksIndexRoute: AuthTasksIndexRoute,
}

const AuthTasksRouteWithChildren = AuthTasksRoute._addFileChildren(
  AuthTasksRouteChildren,
)

interface AuthRouteChildren {
  AuthMapRoute: typeof AuthMapRoute
  AuthTasksRoute: typeof AuthTasksRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
  AuthAdminBreakGlassRoute: typeof AuthAdminBreakGlassRoute
  AuthAdminStuckStepsRoute: typeof AuthAdminStuckStepsRoute
  AuthDirectoryCompanyIdRoute: typeof AuthDirectoryCompanyIdRoute
  AuthDirectoryNewRoute: typeof AuthDirectoryNewRoute
  AuthMasterCountriesRoute: typeof AuthMasterCountriesRoute
  AuthMasterFuelTypesRoute: typeof AuthMasterFuelTypesRoute
  AuthMasterIndustryTypesRoute: typeof AuthMasterIndustryTypesRoute
  AuthMasterMeterSizesRoute: typeof AuthMasterMeterSizesRoute
  AuthMasterMrsSpecsRoute: typeof AuthMasterMrsSpecsRoute
  AuthMasterOrganisationRoute: typeof AuthMasterOrganisationRoute
  AuthMasterReasonCategoriesRoute: typeof AuthMasterReasonCategoriesRoute
  AuthMasterReferenceDocumentsRoute: typeof AuthMasterReferenceDocumentsRoute
  AuthMasterSegmentsRoute: typeof AuthMasterSegmentsRoute
  AuthMasterUnitsRoute: typeof AuthMasterUnitsRoute
  AuthMasterUsersRoute: typeof AuthMasterUsersRoute
  AuthReportsAgeingRoute: typeof AuthReportsAgeingRoute
  AuthReportsFunnelRoute: typeof AuthReportsFunnelRoute
  AuthReportsGasDemandRoute: typeof AuthReportsGasDemandRoute
  AuthReportsNolOutcomesRoute: typeof AuthReportsNolOutcomesRoute
  AuthReportsSurveyProductivityRoute: typeof AuthReportsSurveyProductivityRoute
  AuthDirectoryIndexRoute: typeof AuthDirectoryIndexRoute
  AuthReportsIndexRoute: typeof AuthReportsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthMapRoute: AuthMapRoute,
  AuthTasksRoute: AuthTasksRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
  AuthAdminBreakGlassRoute: AuthAdminBreakGlassRoute,
  AuthAdminStuckStepsRoute: AuthAdminStuckStepsRoute,
  AuthDirectoryCompanyIdRoute: AuthDirectoryCompanyIdRoute,
  AuthDirectoryNewRoute: AuthDirectoryNewRoute,
  AuthMasterCountriesRoute: AuthMasterCountriesRoute,
  AuthMasterFuelTypesRoute: AuthMasterFuelTypesRoute,
  AuthMasterIndustryTypesRoute: AuthMasterIndustryTypesRoute,
  AuthMasterMeterSizesRoute: AuthMasterMeterSizesRoute,
  AuthMasterMrsSpecsRoute: AuthMasterMrsSpecsRoute,
  AuthMasterOrganisationRoute: AuthMasterOrganisationRoute,
  AuthMasterReasonCategoriesRoute: AuthMasterReasonCategoriesRoute,
  AuthMasterReferenceDocumentsRoute: AuthMasterReferenceDocumentsRoute,
  AuthMasterSegmentsRoute: AuthMasterSegmentsRoute,
  AuthMasterUnitsRoute: AuthMasterUnitsRoute,
  AuthMasterUsersRoute: AuthMasterUsersRoute,
  AuthReportsAgeingRoute: AuthReportsAgeingRoute,
  AuthReportsFunnelRoute: AuthReportsFunnelRoute,
  AuthReportsGasDemandRoute: AuthReportsGasDemandRoute,
  AuthReportsNolOutcomesRoute: AuthReportsNolOutcomesRoute,
  AuthReportsSurveyProductivityRoute: AuthReportsSurveyProductivityRoute,
  AuthDirectoryIndexRoute: AuthDirectoryIndexRoute,
  AuthReportsIndexRoute: AuthReportsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
