/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthMapRouteImport } from './routes/_auth/map'
import { Route as AuthDirectoryIndexRouteImport } from './routes/_auth/directory/index'
import { Route as AuthDirectoryCompanyIdRouteImport } from './routes/_auth/directory/$companyId'
import { Route as AuthDirectoryNewRouteImport } from './routes/_auth/directory/new'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMapRoute = AuthMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDirectoryIndexRoute = AuthDirectoryIndexRouteImport.update({
  id: '/directory/',
  path: '/directory/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDirectoryCompanyIdRoute = AuthDirectoryCompanyIdRouteImport.update({
  id: '/directory/$companyId',
  path: '/directory/$companyId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDirectoryNewRoute = AuthDirectoryNewRouteImport.update({
  id: '/directory/new',
  path: '/directory/new',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/change-password': typeof ChangePasswordRoute
  '/sign-in': typeof SignInRoute
  '/map': typeof AuthMapRoute
  '/directory/$companyId': typeof AuthDirectoryCompanyIdRoute
  '/directory/new': typeof AuthDirectoryNewRoute
  '/directory/': typeof AuthDirectoryIndexRoute
}
export interface FileRoutesByTo {
  '/access-denied': typeof AccessDeniedRoute
  '/change-password': typeof ChangePasswordRoute
  '/sign-in': typeof SignInRoute
  '/map': typeof AuthMapRoute
  '/': typeof AuthIndexRoute
  '/directory/$companyId': typeof AuthDirectoryCompanyIdRoute
  '/directory/new': typeof AuthDirectoryNewRoute
  '/directory': typeof AuthDirectoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/access-denied': typeof AccessDeniedRoute
  '/change-password': typeof ChangePasswordRoute
  '/sign-in': typeof SignInRoute
  '/_auth/map': typeof AuthMapRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/directory/$companyId': typeof AuthDirectoryCompanyIdRoute
  '/_auth/directory/new': typeof AuthDirectoryNewRoute
  '/_auth/directory/': typeof AuthDirectoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/change-password'
    | '/sign-in'
    | '/map'
    | '/directory/$companyId'
    | '/directory/new'
    | '/directory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/access-denied'
    | '/change-password'
    | '/sign-in'
    | '/map'
    | '/'
    | '/directory/$companyId'
    | '/directory/new'
    | '/directory'
  id:
    | '__root__'
    | '/_auth'
    | '/access-denied'
    | '/change-password'
    | '/sign-in'
    | '/_auth/map'
    | '/_auth/'
    | '/_auth/directory/$companyId'
    | '/_auth/directory/new'
    | '/_auth/directory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AccessDeniedRoute: typeof AccessDeniedRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/map': {
      id: '/_auth/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthMapRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/directory/': {
      id: '/_auth/directory/'
      path: '/directory'
      fullPath: '/directory/'
      preLoaderRoute: typeof AuthDirectoryIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/directory/$companyId': {
      id: '/_auth/directory/$companyId'
      path: '/directory/$companyId'
      fullPath: '/directory/$companyId'
      preLoaderRoute: typeof AuthDirectoryCompanyIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/directory/new': {
      id: '/_auth/directory/new'
      path: '/directory/new'
      fullPath: '/directory/new'
      preLoaderRoute: typeof AuthDirectoryNewRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthMapRoute: typeof AuthMapRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthDirectoryCompanyIdRoute: typeof AuthDirectoryCompanyIdRoute
  AuthDirectoryNewRoute: typeof AuthDirectoryNewRoute
  AuthDirectoryIndexRoute: typeof AuthDirectoryIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthMapRoute: AuthMapRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthDirectoryCompanyIdRoute: AuthDirectoryCompanyIdRoute,
  AuthDirectoryNewRoute: AuthDirectoryNewRoute,
  AuthDirectoryIndexRoute: AuthDirectoryIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
